// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const DB_ENV = process.env.DB_ENV || "local";
const isLive = DB_ENV === "live";
const env = (key) => process.env[isLive ? `LIVE_${key}` : key] ?? process.env[key];
const envNumber = (key, fallback) => {
    const value = Number(env(key));
    return Number.isFinite(value) && value > 0 ? value : fallback;
};
const encode = (value) => encodeURIComponent(String(value ?? ""));

const buildMysqlUrl = () => {
    const explicitUrl = isLive
        ? (process.env.LIVE_DATABASE_URL || process.env.DATABASE_URL)
        : process.env.DATABASE_URL;

    if (explicitUrl) {
        return explicitUrl;
    }

    const host = env("DATABASE_HOST");
    const database = env("DATABASE_NAME");
    const user = env("DATABASE_USER");

    if (!host || !database || !user) {
        return undefined;
    }

    const password = encode(env("DATABASE_PASSWORD"));
    const port = envNumber("DATABASE_PORT", 3306);

    return `mysql://${encode(user)}:${password}@${host}:${port}/${encode(database)}`;
};

export default defineConfig({
    schema: "prisma/schema.prisma",
    migrations: {
        path: "prisma/migrations",
    },
    datasource: {
        url: buildMysqlUrl(),
    },
});
