INSERT IGNORE INTO ingredient (name, image, category, status, createdAt, updatedAt) VALUES
('Tomato', NULL, 'Vegetable', 'ACTIVE', NOW(), NOW()),
('Onion', NULL, 'Vegetable', 'ACTIVE', NOW(), NOW()),
('Potato', NULL, 'Vegetable', 'ACTIVE', NOW(), NOW()),
('Garlic', NULL, 'Vegetable', 'ACTIVE', NOW(), NOW()),
('Ginger', NULL, 'Vegetable', 'ACTIVE', NOW(), NOW()),
('Green Chilli', NULL, 'Vegetable', 'ACTIVE', NOW(), NOW()),
('Capsicum', NULL, 'Vegetable', 'ACTIVE', NOW(), NOW()),
('Carrot', NULL, 'Vegetable', 'ACTIVE', NOW(), NOW()),
('Cabbage', NULL, 'Vegetable', 'ACTIVE', NOW(), NOW()),
('Cauliflower', NULL, 'Vegetable', 'ACTIVE', NOW(), NOW()),

('Spinach', NULL, 'Vegetable', 'ACTIVE', NOW(), NOW()),
('Fenugreek Leaves', NULL, 'Vegetable', 'ACTIVE', NOW(), NOW()),
('Coriander Leaves', NULL, 'Vegetable', 'ACTIVE', NOW(), NOW()),
('Mint Leaves', NULL, 'Vegetable', 'ACTIVE', NOW(), NOW()),
('Peas', NULL, 'Vegetable', 'ACTIVE', NOW(), NOW()),
('Beans', NULL, 'Vegetable', 'ACTIVE', NOW(), NOW()),
('Brinjal', NULL, 'Vegetable', 'ACTIVE', NOW(), NOW()),
('Radish', NULL, 'Vegetable', 'ACTIVE', NOW(), NOW()),
('Beetroot', NULL, 'Vegetable', 'ACTIVE', NOW(), NOW()),
('Sweet Corn', NULL, 'Vegetable', 'ACTIVE', NOW(), NOW()),

('Paneer', NULL, 'Dairy', 'ACTIVE', NOW(), NOW()),
('Milk', NULL, 'Dairy', 'ACTIVE', NOW(), NOW()),
('Butter', NULL, 'Dairy', 'ACTIVE', NOW(), NOW()),
('Cheese', NULL, 'Dairy', 'ACTIVE', NOW(), NOW()),
('Curd', NULL, 'Dairy', 'ACTIVE', NOW(), NOW()),
('Cream', NULL, 'Dairy', 'ACTIVE', NOW(), NOW()),

('Chicken', NULL, 'Meat', 'ACTIVE', NOW(), NOW()),
('Mutton', NULL, 'Meat', 'ACTIVE', NOW(), NOW()),
('Fish', NULL, 'Meat', 'ACTIVE', NOW(), NOW()),
('Egg', NULL, 'Meat', 'ACTIVE', NOW(), NOW()),

('Rice', NULL, 'Grain', 'ACTIVE', NOW(), NOW()),
('Basmati Rice', NULL, 'Grain', 'ACTIVE', NOW(), NOW()),
('Wheat Flour', NULL, 'Grain', 'ACTIVE', NOW(), NOW()),
('Maida', NULL, 'Grain', 'ACTIVE', NOW(), NOW()),
('Semolina', NULL, 'Grain', 'ACTIVE', NOW(), NOW()),
('Oats', NULL, 'Grain', 'ACTIVE', NOW(), NOW()),

('Salt', NULL, 'Spice', 'ACTIVE', NOW(), NOW()),
('Black Pepper', NULL, 'Spice', 'ACTIVE', NOW(), NOW()),
('Turmeric', NULL, 'Spice', 'ACTIVE', NOW(), NOW()),
('Red Chilli Powder', NULL, 'Spice', 'ACTIVE', NOW(), NOW()),
('Coriander Powder', NULL, 'Spice', 'ACTIVE', NOW(), NOW()),
('Cumin Seeds', NULL, 'Spice', 'ACTIVE', NOW(), NOW()),
('Mustard Seeds', NULL, 'Spice', 'ACTIVE', NOW(), NOW()),
('Garam Masala', NULL, 'Spice', 'ACTIVE', NOW(), NOW()),
('Chaat Masala', NULL, 'Spice', 'ACTIVE', NOW(), NOW()),
('Kasuri Methi', NULL, 'Spice', 'ACTIVE', NOW(), NOW()),

('Sugar', NULL, 'Sweetener', 'ACTIVE', NOW(), NOW()),
('Jaggery', NULL, 'Sweetener', 'ACTIVE', NOW(), NOW()),
('Honey', NULL, 'Sweetener', 'ACTIVE', NOW(), NOW()),

('Cooking Oil', NULL, 'Oil', 'ACTIVE', NOW(), NOW()),
('Mustard Oil', NULL, 'Oil', 'ACTIVE', NOW(), NOW()),
('Olive Oil', NULL, 'Oil', 'ACTIVE', NOW(), NOW()),
('Ghee', NULL, 'Oil', 'ACTIVE', NOW(), NOW()),

('Tomato Ketchup', NULL, 'Sauce', 'ACTIVE', NOW(), NOW()),
('Soy Sauce', NULL, 'Sauce', 'ACTIVE', NOW(), NOW()),
('Chilli Sauce', NULL, 'Sauce', 'ACTIVE', NOW(), NOW()),
('Vinegar', NULL, 'Sauce', 'ACTIVE', NOW(), NOW()),

('Bread', NULL, 'Bakery', 'ACTIVE', NOW(), NOW()),
('Burger Bun', NULL, 'Bakery', 'ACTIVE', NOW(), NOW()),
('Pizza Base', NULL, 'Bakery', 'ACTIVE', NOW(), NOW()),

('Banana', NULL, 'Fruit', 'ACTIVE', NOW(), NOW()),
('Apple', NULL, 'Fruit', 'ACTIVE', NOW(), NOW()),
('Mango', NULL, 'Fruit', 'ACTIVE', NOW(), NOW()),
('Orange', NULL, 'Fruit', 'ACTIVE', NOW(), NOW()),
('Pineapple', NULL, 'Fruit', 'ACTIVE', NOW(), NOW()),
('Grapes', NULL, 'Fruit', 'ACTIVE', NOW(), NOW()),

('Dry Fruits Mix', NULL, 'Dry Fruit', 'ACTIVE', NOW(), NOW()),
('Cashew', NULL, 'Dry Fruit', 'ACTIVE', NOW(), NOW()),
('Almond', NULL, 'Dry Fruit', 'ACTIVE', NOW(), NOW()),
('Raisin', NULL, 'Dry Fruit', 'ACTIVE', NOW(), NOW()),
('Pistachio', NULL, 'Dry Fruit', 'ACTIVE', NOW(), NOW()),

('Noodles', NULL, 'Packaged', 'ACTIVE', NOW(), NOW()),
('Pasta', NULL, 'Packaged', 'ACTIVE', NOW(), NOW()),
('Cornflakes', NULL, 'Packaged', 'ACTIVE', NOW(), NOW()),

('Chocolate', NULL, 'Dessert', 'ACTIVE', NOW(), NOW()),
('Ice Cream', NULL, 'Dessert', 'ACTIVE', NOW(), NOW()),
('Custard Powder', NULL, 'Dessert', 'ACTIVE', NOW(), NOW()),

('Water', NULL, 'Beverage', 'ACTIVE', NOW(), NOW()),
('Tea Leaves', NULL, 'Beverage', 'ACTIVE', NOW(), NOW()),
('Coffee Powder', NULL, 'Beverage', 'ACTIVE', NOW(), NOW()),
('Green Tea', NULL, 'Beverage', 'ACTIVE', NOW(), NOW());